import type { Metadata } from "next";
// import "../../(web)/global.css";

// const poppins = Poppins({
//   subsets: ['latin'],
//   weight: ['400', '500', '700', '900'],
//   style: ['italic', 'normal'],
//   variable: "--font-poppins"
// })

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        {children}

      </body>
    </html>
  );
}
